open_path:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    path:
      required: true
      example: "C:\\test\\image.png"
      selector:
        text:
open_url:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    url:
      required: true
      example: "https://www.home-assistant.io"
      selector:
        text:
send_keypress:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    key:
      required: true
      example: "audio_play"
      selector:
        text:
send_text:
  fields:
    bridge:
      required: true
      selector:
        device:
          integration: system_bridge
    text:
      required: true
      example: "Hello world"
      selector:
        text:
power_command:
  name: Power Command
  description: Sends a power command to the system.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    command:
      name: Command
      description: Command to call.
      required: true
      example: "sleep"
      selector:
        select:
          options:
            - "hibernate"
            - "lock"
            - "logout"
            - "restart"
            - "shutdown"
            - "sleep"
