open_path:
  name: Open Path
  description: Open a file on the server using the default application.
  fields:
    bridge:
      name: Bridge
      description: The server to talk to.
      required: true
      selector:
        device:
          integration: system_bridge
    path:
      name: Path
      description: Path to open.
      required: true
      example: "C:\\test\\image.png"
      selector:
        text:
open_url:
  name: Open URL
  description: Open a URL on the server using the default application.
  fields:
    bridge:
      name: Bridge
      description: The server to talk to.
      required: true
      selector:
        device:
          integration: system_bridge
    url:
      name: URL
      description: URL to open.
      required: true
      example: "https://www.home-assistant.io"
      selector:
        text:
send_keypress:
  name: Send Keyboard Keypress
  description: Sends a keyboard keypress.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    key:
      name: Key
      description: "Key to press. List available here: http://robotjs.io/docs/syntax#keys"
      required: true
      example: "audio_play"
      selector:
        text:
send_text:
  name: Send Keyboard Text
  description: Sends text for the server to type.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    text:
      name: Text
      description: "Text to type."
      required: true
      example: "Hello world"
      selector:
        text:
control_power:
  name: Control Power
  description: Sends commands to control the power state of the server.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    command:
      name: Command
      description: "Command to send."
      required: true
      default: "shutdown"
      selector:
        select:
          options:
            - "sleep"
            - "hibernate"
            - "restart"
            - "shutdown"
            - "lock"
            - "logout"
send_notification:
  name: Send Notification
  description: Send notifications to the desktop.
  fields:
    bridge:
      name: Bridge
      description: The server to send the command to.
      required: true
      selector:
        device:
          integration: system_bridge
    title:
      name: Title
      description: "Title of the notification."
      required: true
      example: "Hello world"
      selector:
        text:
    message:
      name: Message
      description: "Message of the notification."
      required: false
      example: "Hello world"
      selector:
        text:
    icon:
      name: Icon
      description: "Icon of the notification."
      required: false
      selector:
        text:
    image:
      name: Image
      description: "Image of the notification."
      required: false
      selector:
        text:
    timeout:
      name: Timeout
      description: "Timeout of the notification."
      required: false
      default: 5
      selector:
        number:
          min: 0
          max: 360

