# Describes the format for available iCloud services

reset:
  description: Reset the iCloud account and re build it.
  fields:
    account_name:
      description: Your iCloud account name or username.
      example: 'steve@apple.com'

update:
  description: Update iCloud devices.
  fields:
    account_name:
      description: Your iCloud account name or username.
      example: 'steve@apple.com'

play_sound:
  description: Play sound on an Apple device.
  fields:
    account_name:
      description: (required) Your iCloud account name or username.
      example: 'steve@apple.com'
    device_name:
      description: (required) The name of the Apple device to play a sound.
      example: 'stevesiphone'

display_message:
  description: Display a message on an Apple device.
  fields:
    account_name:
      description: (required) Your iCloud account name or username.
      example: 'steve@apple.com'
    device_name:
      description: (required) The name of the Apple device to display the message.
      example: 'stevesiphone'
    message:
      description: (required) The content of your message.
    sound:
      description: To make a sound when displaying the message (boolean).
      example: 'true'

lost_device:
  description: Make an Apple device in lost state.
  fields:
    account_name:
      description: (required) Your iCloud account name or username.
      example: 'steve@apple.com'
    device_name:
      description: (required) The name of the Apple device to set lost.
      example: 'stevesiphone'
    number:
      description: (required) The phone number to call in lost mode (must contain country code).
      example: '+33450020100'
    message:
      description: (required) The message to display in lost mode.
      example: 'Call me'

