# Describes the format for available image_processing services

scan:
  description: Processing immediately a image

  fields:
    entity_id:
      description: Name(s) of entities to scan immediately
      example: 'image_processing.alpr_garage'
