next_down_position:
  fields:
    entity_id:
      example: "cover.master"
      default: "cover.master"
      required: true

next_up_position:
  fields:
    entity_id:
      example: "cover.master"
      default: "cover.master"
      required: true
