add_torrent:
  description: Add a new torrent to download (URL, magnet link).
  fields:
    name:
      description: client name as entered during entry config
      example: Deluge
    torrent:
      description: URL, magnet link or Base64 encoded file.
      example: http://releases.ubuntu.com/19.04/ubuntu-19.04-desktop-amd64.iso.torrent
