# Describes the format for available homekit_controller services

thread_provision:
  name: Provision Thread network credentials to a device
  description: >-
    Write credentials to the Thread Control Point on the specified entity.
  fields:
    hkid:
      name: HomeKit pairing ID
      description: HomeKit accessory pairing ID, IEEE address
      example: "AA:BB:CC:DD:EE:FF"
      selector:
        text:
