# Describes the format for available options

set_option:
  description: Select an option

  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'fan.option'

    option:
      description: Name of the option to select
      example: 'Level 1'
