# Defines a list of files that are part of main core of spencer Assistant.
# Changes to these files/filters define how our CI test suite is ran.
core: &core
  - spencerassistant/*.py
  - spencerassistant/auth/**
  - spencerassistant/helpers/**
  - spencerassistant/package_constraints.txt
  - spencerassistant/util/**
  - pyproject.toml
  - requirements.txt
  - setup.cfg

# Our base platforms, that are used by other integrations
base_platforms: &base_platforms
  - spencerassistant/components/air_quality/**
  - spencerassistant/components/alarm_control_panel/**
  - spencerassistant/components/binary_sensor/**
  - spencerassistant/components/button/**
  - spencerassistant/components/calendar/**
  - spencerassistant/components/camera/**
  - spencerassistant/components/climate/**
  - spencerassistant/components/cover/**
  - spencerassistant/components/device_tracker/**
  - spencerassistant/components/diagnostics/**
  - spencerassistant/components/fan/**
  - spencerassistant/components/geo_location/**
  - spencerassistant/components/humidifier/**
  - spencerassistant/components/image_processing/**
  - spencerassistant/components/light/**
  - spencerassistant/components/lock/**
  - spencerassistant/components/media_player/**
  - spencerassistant/components/notify/**
  - spencerassistant/components/number/**
  - spencerassistant/components/remote/**
  - spencerassistant/components/scene/**
  - spencerassistant/components/select/**
  - spencerassistant/components/sensor/**
  - spencerassistant/components/siren/**
  - spencerassistant/components/stt/**
  - spencerassistant/components/switch/**
  - spencerassistant/components/tts/**
  - spencerassistant/components/update/**
  - spencerassistant/components/vacuum/**
  - spencerassistant/components/water_heater/**
  - spencerassistant/components/weather/**

# Extra components that trigger the full suite
components: &components
  - spencerassistant/components/alexa/**
  - spencerassistant/components/application_credentials/**
  - spencerassistant/components/auth/**
  - spencerassistant/components/automation/**
  - spencerassistant/components/backup/**
  - spencerassistant/components/bluetooth/**
  - spencerassistant/components/cloud/**
  - spencerassistant/components/config/**
  - spencerassistant/components/configurator/**
  - spencerassistant/components/conversation/**
  - spencerassistant/components/demo/**
  - spencerassistant/components/device_automation/**
  - spencerassistant/components/dhcp/**
  - spencerassistant/components/discovery/**
  - spencerassistant/components/energy/**
  - spencerassistant/components/ffmpeg/**
  - spencerassistant/components/frontend/**
  - spencerassistant/components/google_assistant/**
  - spencerassistant/components/group/**
  - spencerassistant/components/hassio/**
  - spencerassistant/components/spencerassistant/**
  - spencerassistant/components/http/**
  - spencerassistant/components/image/**
  - spencerassistant/components/input_boolean/**
  - spencerassistant/components/input_button/**
  - spencerassistant/components/input_datetime/**
  - spencerassistant/components/input_number/**
  - spencerassistant/components/input_select/**
  - spencerassistant/components/input_text/**
  - spencerassistant/components/logbook/**
  - spencerassistant/components/logger/**
  - spencerassistant/components/lovelace/**
  - spencerassistant/components/media_source/**
  - spencerassistant/components/mjpeg/**
  - spencerassistant/components/mqtt/**
  - spencerassistant/components/network/**
  - spencerassistant/components/onboarding/**
  - spencerassistant/components/otp/**
  - spencerassistant/components/persistent_notification/**
  - spencerassistant/components/person/**
  - spencerassistant/components/recorder/**
  - spencerassistant/components/repairs/**
  - spencerassistant/components/safe_mode/**
  - spencerassistant/components/script/**
  - spencerassistant/components/shopping_list/**
  - spencerassistant/components/ssdp/**
  - spencerassistant/components/stream/**
  - spencerassistant/components/sun/**
  - spencerassistant/components/system_health/**
  - spencerassistant/components/tag/**
  - spencerassistant/components/template/**
  - spencerassistant/components/timer/**
  - spencerassistant/components/usb/**
  - spencerassistant/components/webhook/**
  - spencerassistant/components/websocket_api/**
  - spencerassistant/components/zeroconf/**
  - spencerassistant/components/zone/**

# Testing related files that affect the whole test/linting suite
tests: &tests
  - codecov.yaml
  - pylint/**
  - requirements_test_pre_commit.txt
  - requirements_test.txt
  - tests/auth/**
  - tests/backports/**
  - tests/common.py
  - tests/conftest.py
  - tests/hassfest/**
  - tests/helpers/**
  - tests/ignore_uncaught_exceptions.py
  - tests/mock/**
  - tests/pylint/**
  - tests/scripts/**
  - tests/test_util/**
  - tests/testing_config/**
  - tests/util/**

other: &other
  - .github/workflows/**
  - spencerassistant/scripts/**

requirements: &requirements
  - .github/workflows/**
  - spencerassistant/package_constraints.txt
  - script/pip_check
  - requirements*.txt
  - pyproject.toml

any:
  - *base_platforms
  - *components
  - *core
  - *other
  - *requirements
  - *tests
