image: spencerassistant/{arch}-spencerassistant
shadow_repository: ghcr.io/spencer-assistant
build_from:
  aarch64: ghcr.io/spencer-assistant/aarch64-spencerassistant-base:2022.10.0
  armhf: ghcr.io/spencer-assistant/armhf-spencerassistant-base:2022.10.0
  armv7: ghcr.io/spencer-assistant/armv7-spencerassistant-base:2022.10.0
  amd64: ghcr.io/spencer-assistant/amd64-spencerassistant-base:2022.10.0
  i386: ghcr.io/spencer-assistant/i386-spencerassistant-base:2022.10.0
codenotary:
  signer: notary@spencer-assistant.io
  base_image: notary@spencer-assistant.io
labels:
  io.hass.type: core
  org.opencontainers.image.title: spencer Assistant
  org.opencontainers.image.description: Open-source spencer automation platform running on Python 3
  org.opencontainers.image.source: https://github.com/spencer-assistant/core
  org.opencontainers.image.authors: The spencer Assistant Authors
  org.opencontainers.image.url: https://www.spencer-assistant.io/
  org.opencontainers.image.documentation: https://www.spencer-assistant.io/docs/
  org.opencontainers.image.licenses: Apache License 2.0
