# Describes the format for available fan services

set_speed:
  description: Sets fan speed.
  fields:
    entity_id:
      description: Name(s) of the entities to set
      example: 'fan.living_room'
    speed:
      description: Speed setting
      example: 'low'

turn_on:
  description: Turns fan on.
  fields:
    entity_id:
      description: Names(s) of the entities to turn on
      example: 'fan.living_room'
    speed:
      description: Speed setting
      example: 'high'

turn_off:
  description: Turns fan off.
  fields:
    entity_id:
      description: Names(s) of the entities to turn off
      example: 'fan.living_room'

oscillate:
  description: Oscillates the fan.
  fields:
    entity_id:
      description: Name(s) of the entities to oscillate
      example: 'fan.desk_fan'
    oscillating:
      description: Flag to turn on/off oscillation
      example: True

toggle:
  description: Toggle the fan on/off.
  fields:
    entity_id:
      description: Name(s) of the entities to toggle
      example: 'fan.living_room'

set_direction:
  description: Set the fan rotation.
  fields:
    entity_id:
      description: Name(s) of the entities to toggle
      example: 'fan.living_room'
    direction:
      description: The direction to rotate. Either 'forward' or 'reverse'
      example: 'forward'

wemo_set_humidity:
  description: Set the target humidity of WeMo humidifier devices.
  fields:
    entity_id:
      description: Names of the WeMo humidifier entities (1 or more entity_ids are required).
      example: 'fan.wemo_humidifier'
    target_humidity:
      description: Target humidity. This is a float value between 0 and 100, but will be mapped to the humidity levels that WeMo humidifiers support (45, 50, 55, 60, and 100/Max) by rounding the value down to the nearest supported value.
      example: 56.5

wemo_reset_filter_life:
  description: Reset the WeMo Humidifier's filter life to 100%.
  fields:
    entity_id:
      description: Names of the WeMo humidifier entities (1 or more entity_ids are required).
      example: 'fan.wemo_humidifier'
