ptz_control:
  description: Execute a PTZ command
  fields:
    entity_id:
      description: Name of the Reolink camera entity to execute the command on.
      example: 'camera.frontdoor'
    command:
      description: >-
        Command to execute. Possible values are:
        AUTO DOWN FOCUSDEC FOCUSINC LEFT LEFTDOWN LEFTUP
        RIGHT RIGHTDOWN RIGHTUP STOP TOPOS UP ZOOMDEC ZOOMINC
      example: LEFTUP
    preset:
      description: In case of the command TOPOS. The available presets are listed as attribute on the camera.
      example:
    speed:
      description: Speed at which the movement takes place.
      example: 25
