# shelly service descriptions.

ota_update:
  name: OTA Update
  description: Trigger an over-the-air (OTA) update.
  target:
    device:
      integration: shelly
    entity:
      integration: none
  fields:
    beta:
      name: Beta
      description: Run firmware update to beta version (if available)
      required: false
      default: false
      example: true
      selector:
        boolean:
