reconnect_client:
  name: Reconnect wireless client
  description: Try to get wireless client to reconnect to UniFi Network
  fields:
    device_id:
      name: Device
      description: Try reconnect client to wireless network
      required: true
      selector:
        device:
          integration: unifi
remove_clients:
  name: Remove clients from the UniFi Network
  description: Clean up clients that has only been associated with the controller for under 15 minutes
remove_old_clients:
  name: Remove old clients from the UniFi Network
  description: Clean up clients that haven't seen the network in the number of days specified
  fields:
    days:
      name: Days
      description: Days since last seen by the controller
      required: true
      default: 90
      selector:
        number:
          min: 30
          max: 1000
          step: 1
          unit_of_measurement: days
