reconnect_client:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: unifi

remove_clients:

change_wlan_password:
  fields:
    hub_name:
      required: true
    wlan_name:
      required: true
    new_password:
      required: true

get_wlan_password:
  fields:
    hub_name:
      required: true
    wlan_name:
      required: true
