# Describes the format for available RainMachine services
disable_program:
  name: Disable program
  description: Disable a program.
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: program
disable_zone:
  name: Disable zone
  description: Disable a zone.
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: zone
enable_program:
  name: Enable program
  description: Enable a program.
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: program
enable_zone:
  name: Enable zone
  description: Enable a zone.
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: zone
pause_watering:
  name: Pause watering
  description: Pause all watering for a number of seconds.
  target:
    device:
      integration: rainmachine
  fields:
    seconds:
      name: Seconds
      description: The time to pause.
      required: true
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
start_program:
  name: Start program
  description: Start a program
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: program
start_zone:
  name: Start zone
  description: Start a zone for a set number of seconds.
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: zone
  fields:
    zone_run_time:
      name: Zone run time
      description: The number of seconds to run the zone.
      default: 600
      selector:
        number:
          min: 1
          max: 86400
          mode: box
stop_all:
  name: Stop all
  description: Stop all watering activities.
  target:
    device:
      integration: rainmachine
stop_program:
  name: Stop program
  description: Start a program
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: program
stop_zone:
  name: Stop zone
  description: Stop a zone
  target:
    entity:
      integration: rainmachine
      domain: switch
      device_class: zone
unpause_watering:
  name: Unpause watering
  description: Unpause all watering.
  target:
    device:
      integration: rainmachine
