publish:
  description: Publish a message to an MQTT topic

  fields:
    topic:
      description: Topic to publish payload
      example: /homeassistant/hello

    payload:
      description: Payload to publish
      example: This is great

    payload_template:
      description: Template to render as payload value. Ignored if payload given.
      example: "{{ states('sensor.temperature') }}"

    payload_file_path:
      description: Path to a file within the local www directory to be published as binary payload.
      example: "snapshot.jpg"

    qos:
      description: Quality of Service
      example: 2
      values:
        - 0
        - 1
        - 2
      default: 0

    retain:
      description: If message should have the retain flag set.
      example: true
      default: false
