# Describes the format for available analog switch services

decrement:
  description: Decrement the value of an analog switch entity by its stepping.
  fields:
    entity_id:
      description: Entity id of the analog switch that should be decremented.
      example: analog_switch.volume
increment:
  description: Increment the value of an analog switch entity by its stepping.
  fields:
    entity_id:
      description: Entity id of the analog switch that should be incremented.
      example: analog_switch.volume
set_value:
  description: Set the value of an analog switch entity.
  fields:
    entity_id:
      description: Entity id of the analog switch to set the new value.
      example: analog_switch.volume
    value:
      description: The target value the entity should be set to.
      example: 42
