create_item:
  target:
    entity:
      domain: todo
      supported_features:
        - todo.TodoListEntityFeature.CREATE_TODO_ITEM
  fields:
    summary:
      required: true
      example: "Submit Income Tax Return"
      selector:
        text:
    status:
      required: false
      example: "needs_action"
      selector:
        select:
          translation_key: status
          options:
            - needs_action
            - completed
update_item:
  target:
    entity:
      domain: todo
      supported_features:
        - todo.TodoListEntityFeature.UPDATE_TODO_ITEM
  fields:
    uid:
      required: true
      selector:
        text:
    summary:
      required: true
      example: "Submit Income Tax Return"
      selector:
        text:
    status:
      required: false
      example: "needs_action"
      selector:
        select:
          translation_key: status
          options:
            - needs_action
            - completed
delete_item:
  target:
    entity:
      domain: todo
      supported_features:
        - todo.TodoListEntityFeature.DELETE_TODO_ITEM
  fields:
    uids:
      required: true
      selector:
        object:
move_item:
  target:
    entity:
      domain: todo
      supported_features:
        - todo.TodoListEntityFeature.MOVE_TODO_ITEM
  fields:
    uid:
      required: true
      selector:
        text:
    previous:
      required: false
      selector:
        text:
