update_setting:
  name: Update the value of a setting on a Vizio media player device
  description: Update the value of a setting on a Vizio media player device.
  target:
    entity:
      integration: vizio
      domain: media_player
  fields:
    setting_type:
      description: The type of setting to be changed. Available types are listed in the `setting_types` property.
      example: "audio"
      selector:
        text:
    setting_name:
      description: The name of the setting to be changed. Available settings for a given setting_type are listed in the `<setting_type>_settings` property.
      example: "eq"
      selector:
        text:
    new_value:
      description: The new value for the setting
      example: "Music"
      selector:
        text:
