# Describes the format for available TTS services

knovvu_say:
  name: Say an TTS message with knovvu
  description: Say something using text-to-speech on a media player with knovvu.
  fields:
    entity_id:
      name: Entity
      description: Name(s) of media player entities.
      required: true
      selector:
        entity:
          domain: media_player
    message:
      name: Message
      description: Text to speak on devices.
      example: "Benim adım Mert"
      required: true
      selector:
        text:
