version: 2
jobs:
  pre-install-all-requirements:
    docker:
    - image: circleci/python:3.5.5-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt" }}-{{
          checksum "requirements_all.txt" }}-{{ checksum "requirements_test.txt" }}-
    - run:
        name: install dependencies
        command: |+
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools
          pip install -q --progress-bar off -r requirements_all.txt -c homeassistant/package_constraints.txt
          pip install -q --progress-bar off -r requirements_test.txt -c homeassistant/package_constraints.txt

        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt"
          }}-{{ checksum "requirements_all.txt" }}-{{ checksum "requirements_test.txt"
          }}-
  pre-test 3.6:
    docker:
    - image: circleci/python:3.6-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.6-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools


          pip install -q --progress-bar off -r requirements_test_all.txt -c homeassistant/package_constraints.txt
        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.6-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
  static-check:
    docker:
    - image: circleci/python:3.5.5-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt" }}--{{
          checksum "requirements_test.txt" }}-
    - run:
        name: install dependencies
        command: |+
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools

          pip install -q --progress-bar off -r requirements_test.txt -c homeassistant/package_constraints.txt

        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt"
          }}--{{ checksum "requirements_test.txt" }}-
    - run:
        name: run static check
        command: |
          . venv/bin/activate
          flake8
    - run:
        name: run static type check
        command: |
          . venv/bin/activate
          TYPING_FILES=$(cat mypyrc)
          mypy $TYPING_FILES
    - run:
        name: install
        command: |
          . venv/bin/activate
          pip install -q --progress-bar off -e .
    - run:
        name: validate manifests
        command: |
          . venv/bin/activate
          python -m script.hassfest validate
    - run:
        name: run gen_requirements_all
        command: |
          . venv/bin/activate
          python script/gen_requirements_all.py validate
  pylint:
    docker:
    - image: circleci/python:3.5.5-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    parallelism: 2
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt" }}-{{
          checksum "requirements_all.txt" }}-{{ checksum "requirements_test.txt" }}-
    - run:
        name: install dependencies
        command: |+
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools
          pip install -q --progress-bar off -r requirements_all.txt -c homeassistant/package_constraints.txt
          pip install -q --progress-bar off -r requirements_test.txt -c homeassistant/package_constraints.txt

        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt"
          }}-{{ checksum "requirements_all.txt" }}-{{ checksum "requirements_test.txt"
          }}-
    - run:
        name: install
        command: |
          . venv/bin/activate
          pip install -q --progress-bar off -e .
    - run:
        name: run pylint
        command: |
          . venv/bin/activate
          PYFILES=$(circleci tests glob "homeassistant/**/*.py" | circleci tests split)
          pylint ${PYFILES}
        no_output_timeout: 15m
  pre-test 3.7:
    docker:
    - image: circleci/python:3.7-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.7-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools


          pip install -q --progress-bar off -r requirements_test_all.txt -c homeassistant/package_constraints.txt
        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.7-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
  pre-test 3.5.5:
    docker:
    - image: circleci/python:3.5.5-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools


          pip install -q --progress-bar off -r requirements_test_all.txt -c homeassistant/package_constraints.txt
        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt"
          }}---{{ checksum "requirements_test_all.txt" }}
  test 3.5.5:
    docker:
    - image: circleci/python:3.5.5-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    parallelism: 2
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools


          pip install -q --progress-bar off -r requirements_test_all.txt -c homeassistant/package_constraints.txt
        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.5.5-stretch-{{ checksum "homeassistant/package_constraints.txt"
          }}---{{ checksum "requirements_test_all.txt" }}
    - run:
        name: install
        command: |
          . venv/bin/activate
          pip install -q --progress-bar off -e .
    - run:
        name: run tests with code coverage
        command: |
          . venv/bin/activate
          CC_SWITCH="--cov --cov-report="
          TESTFILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
          pytest --timeout=9 --durations=10 --junitxml=test-reports/homeassistant/results.xml -qq -o junit_family=xunit2 -o junit_suite_name=homeassistant -o console_output_style=count -p no:sugar $CC_SWITCH -- ${TESTFILES}
          script/check_dirty
          codecov
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: htmlcov
        destination: cov-reports
    - store_artifacts:
        path: test-reports
        destination: test-reports
  test 3.7:
    docker:
    - image: circleci/python:3.7-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    parallelism: 2
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.7-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools


          pip install -q --progress-bar off -r requirements_test_all.txt -c homeassistant/package_constraints.txt
        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.7-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install
        command: |
          . venv/bin/activate
          pip install -q --progress-bar off -e .
    - run:
        name: run tests with code coverage
        command: |
          . venv/bin/activate
          CC_SWITCH="--cov --cov-report="
          TESTFILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
          pytest --timeout=9 --durations=10 --junitxml=test-reports/homeassistant/results.xml -qq -o junit_family=xunit2 -o junit_suite_name=homeassistant -o console_output_style=count -p no:sugar $CC_SWITCH -- ${TESTFILES}
          script/check_dirty
          codecov
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: htmlcov
        destination: cov-reports
    - store_artifacts:
        path: test-reports
        destination: test-reports
  upload-translations:
    machine: true
    steps:
    - checkout
    - run:
        name: upload english translations
        command: |
          pyenv versions
          pyenv global 3.5.2
          docker pull lokalise/lokalise-cli@sha256:2198814ebddfda56ee041a4b427521757dd57f75415ea9693696a64c550cef21
          script/translations_upload
  test 3.6:
    docker:
    - image: circleci/python:3.6-stretch
    - image: circleci/buildpack-deps:stretch
    working_directory: ~/repo
    parallelism: 2
    steps:
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y --no-install-recommends
          libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev
          libswscale-dev libswresample-dev libavfilter-dev
    - restore_cache:
        keys:
        - v1-3.6-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -q -U pip
          pip install -q -U setuptools


          pip install -q --progress-bar off -r requirements_test_all.txt -c homeassistant/package_constraints.txt
        no_output_timeout: 15m
    - save_cache:
        paths:
        - ./venv
        key: v1-3.6-stretch-{{ checksum "homeassistant/package_constraints.txt" }}---{{
          checksum "requirements_test_all.txt" }}
    - run:
        name: install
        command: |
          . venv/bin/activate
          pip install -q --progress-bar off -e .
    - run:
        name: run tests with code coverage
        command: |
          . venv/bin/activate
          CC_SWITCH="--cov --cov-report="
          TESTFILES=$(circleci tests glob "tests/**/test_*.py" | circleci tests split --split-by=timings)
          pytest --timeout=9 --durations=10 --junitxml=test-reports/homeassistant/results.xml -qq -o junit_family=xunit2 -o junit_suite_name=homeassistant -o console_output_style=count -p no:sugar $CC_SWITCH -- ${TESTFILES}
          script/check_dirty
          codecov
    - store_test_results:
        path: test-reports
    - store_artifacts:
        path: htmlcov
        destination: cov-reports
    - store_artifacts:
        path: test-reports
        destination: test-reports
workflows:
  version: 2
  build:
    jobs:
    - static-check
    - pre-install-all-requirements:
        requires:
        - static-check
    - pylint:
        requires:
        - pre-install-all-requirements
    - pre-test 3.5.5:
        requires:
        - static-check
    - pre-test 3.6:
        requires:
        - static-check
    - pre-test 3.7:
        requires:
        - static-check
    - test 3.5.5:
        requires:
        - pre-test 3.5.5
    - test 3.6:
        requires:
        - pre-test 3.6
    - test 3.7:
        requires:
        - pre-test 3.7
    - upload-translations:
        filters:
          branches:
            only: dev
        requires:
        - static-check
