sequence_effect:
  description: Set a sequence effect
  target:
    entity:
      integration: tplink
      domain: light
  fields:
    sequence:
      description: List of HSV sequences. (Max 16 Colors)
      example: |
        - [340, 20, 50]
        - [20, 50, 50]
        - [0, 100, 50]
      required: true
      selector:
        object:
    brightness:
      description: Initial brightness (0-100).
      example: 80
      default: 100
      required: false
      selector:
        number:
          min: 1
          step: 1
          max: 100
          unit_of_measurement: "%"
    duration:
      description: Duration (0-5000).
      example: 80
      default: 0
      required: false
      selector:
        number:
          min: 0
          step: 1
          max: 5000
          unit_of_measurement: "ms"
    transition:
      description: Transition (0-6000).
      example: 2000
      default: 0
      required: false
      selector:
        number:
          min: 0
          step: 1
          max: 6000
          unit_of_measurement: "ms"
    fadeoff:
      description: Fade Off (0-3000)
      example: 2000
      default: 0
      required: false
      selector:
        number:
          min: 0
          step: 1
          max: 3000
          unit_of_measurement: "ms"
    segments:
      description: List of Segments
      example: [0, 2, 4, 6, 8]
      default: [0]
      required: false
      selector:
        object:
    spread:
      description: Spread
      example: 1
      default: 0
      required: false
      selector:
        number:
          min: 0
          step: 1
          max: 16
