toggle:
  target:
    entity:
      domain: alert

turn_off:
  target:
    entity:
      domain: alert

turn_on:
  target:
    entity:
      domain: alert

reload:
  name: Reload
  description: Reload the alert configuration.
