toggle:
  name: Toggle
  description: Toggle alert's notifications.
  target:
    entity:
      domain: alert

turn_off:
  name: Turn off
  description: Silence alert's notifications. Affects only current firing, not future firings of the alert.
  target:
    entity:
      domain: alert

turn_on:
  name: Turn on
  description: Reset alert's notifications. Affects only current firing, not future firings of the alert.
  target:
    entity:
      domain: alert

notification_control:
  name: Notification Control
  description: Enable/Disable/Snooze notifications. Affects current and future alert firings.
  target:
    entity:
      domain: alert
  fields:
    enable:
      name: Notifications
      description: Enable, disable or snooze notifications
      example: true
      required: true
      selector:
        select:
          options:
            - label: "Enable"
              value: "on"
            - label: "Disable"
              value: "off"
            - label: "Snooze"
              value: "snooze"
    snooze_until:
      name: Snooze until
      description: Notifications will only be sent for alerts that fire after this time.  Should only be set if Notifications is set to "Snooze". Format can be "2000-01-20 04:23:00". Time is parsed as GMT.
      required: false
      selector:
        text:
