add_item:
  description: Adds an item to the shopping list.
  fields:
    name:
      description: The name of the item to add.
      example: Beer
complete_item:
  description: Marks an item as completed in the shopping list. It does not remove the item.
  fields:
    name:
      description: The name of the item to mark as completed.
      example: Beer
incomplete_item:
  description: Marks an item as incomplete in the shopping list.
  fields:
    name:
      description: The name of the item to mark as incomplete.
      example: Beer
complete_all:
  description: Marks all items as completed in the shopping list. It does not remove the items.
incomplete_all:
  description: Marks all items as incomplete in the shopping list.
