set_sleep_number:
  description: Sets the Sleep Number setting of a side of a bed.
  target:
    entity:
      domain: sensor
  fields:
    sleep_number:
      description: The new sleep number setting between 5 and 100 in multiples of 5.  A number not a multiple of 5 will be rounded to the nearest multiple.
      example: "80"
      default: "100"
      selector:
        number:
          min: 5
          max: 100
          step: 5
