# Describes the format for available hue services

hue_activate_scene:
  description: Activate a hue scene stored in the hue hub.
  fields:
    group_name:
      description: Name of hue group/room from the hue app.
      example: "Living Room"
    scene_name:
      description: Name of hue scene from the hue app.
      example: "Energize"

hue_config_sensor:
  description: Set config for binary sensor or sensor.
  fields:
    entity_id:
      description: Name(s) of the entities to set.
      example: "binary_sensor.hue_motion"
    sensitivity:
      description: Set sensitivity for binary sensor motion ( value between 0 and sensitivity max).
      example: 2
    tholdoffset:
      description: Set offset for dark mode into binary sensor motion ( value between 0 and 25000).
      example: 7000
    tholddark:
      description : Set offset to dertermine insufficient level.
      example: 16000
    sunriseoffset:
      description: Set sunrise offset.
      example: -30
    sunsetoffset:
      description: Set sunset offset.
      example: 30
    long:
      description: Longitude
      example: -115.81
    lat:
      description: Latitude
      example: 37.235
    "on":
      description: Enable/Disable sensor.
      example: true
