# Describes the format for available projector services

turn_on:
  description: Turn a projector power on.
  fields:
    entity_id:
      description: Name(s) of entities to turn on.
      example: 'projector.bedroom_ceiling'

turn_off:
  description: Turn a projector power off.
  fields:
    entity_id:
      description: Name(s) of entities to turn off.
      example: 'projector.bedroom_ceiling'