send_message:
  target:
    entity:
      domain: notify
      integration: bring
  fields:
    notification_type:
      example: going_shopping
      required: true
      default: "going_shopping"
      selector:
        select:
          translation_key: "notification_type_selector"
          options:
            - "going_shopping"
            - "changed_list"
            - "shopping_done"
            - "urgent_message"
    item:
      example: Cilantro
      required: false
      selector:
        text:
