get_torrents:
  function: handle_get_torrents
  fields:
    torrent_filter:
      required: true
      example: "all"
      default: "all"
      selector:
        select:
          options:
            - "active"
            - "inactive"
            - "paused"
            - "all"
            - "seeding"
            - "started"
