# Describes the format for available calendar services

todoist_new_task:
  description: Create a new task and add it to a project.
  fields:
    content:
      description: The name of the task.
      example: Pick up the mail
    project:
      description: The name of the project this task should belong to. Defaults to Inbox.
      example: Errands
    labels:
      description: Any labels that you want to apply to this task, separated by a comma.
      example: Chores,Deliveries
    priority:
      description: The priority of this task, from 1 (normal) to 4 (urgent).
      example: 2
    due_date_string:
      description: The day this task is due, in natural language.
      example: "tomorrow"
    due_date_lang:
      description: The language of due_date_string.
      example: "en"
    due_date:
      description: The day this task is due, in format YYYY-MM-DD.
      example: "2018-04-01"

create_event:
  description: Create new event
  fields:
    title:
      description: Event title
      example: My event
    start:
      description: Event start date or datetime (ISO8601 format. See https://en.wikipedia.org/wiki/ISO_8601)
      example: 2018-08-17T10:30:00
    end:
      description: Event start date or datetime (ISO8601 format. See https://en.wikipedia.org/wiki/ISO_8601). Default None
      example: "2018-08-17"
    url:
      description: Event url. Default None
      example: https://www.home-assistant.io
    color:
      description: Event background HTML color in calendar view
      example: aabbcc
    all_day:
      description: Define as an all day event. Default false
      example: true
    description:
      description: Detailed description
      example: This is the description of my event
