set_txt:
  description: Set the TXT record of your duckdns subdomain.
  fields:
    txt:
      description: Peyload for the TXT record.
      example: 'This domain name is reserved for use in documentation'
