# Describes the format for available camera services

turn_off:
  description: Turn off camera.
  fields:
    entity_id:
      description: Entity id.
      example: 'camera.living_room'

turn_on:
  description: Turn on camera.
  fields:
    entity_id:
      description: Entity id.
      example: 'camera.living_room'

enable_motion_detection:
  description: Enable the motion detection in a camera.
  fields:
    entity_id:
      description: Name(s) of entities to enable motion detection.
      example: 'camera.living_room_camera'

disable_motion_detection:
  description: Disable the motion detection in a camera.
  fields:
    entity_id:
      description: Name(s) of entities to disable motion detection.
      example: 'camera.living_room_camera'

snapshot:
  description: Take a snapshot from a camera.
  fields:
    entity_id:
      description: Name(s) of entities to create snapshots from.
      example: 'camera.living_room_camera'
    filename:
      description: Template of a Filename. Variable is entity_id.
      example: '/tmp/snapshot_{{ entity_id }}'

play_stream:
  description: Play camera stream on supported media player.
  fields:
    entity_id:
      description: Name(s) of entities to stream from.
      example: 'camera.living_room_camera'
    media_player:
      description: Name(s) of media player to stream to.
      example: 'media_player.living_room_tv'
    format:
      description: (Optional) Stream format supported by media player.
      example: 'hls'

record:
  description: Record live camera feed.
  fields:
    entity_id:
      description: Name of entities to record.
      example: 'camera.living_room_camera'
    filename:
      description: Template of a Filename. Variable is entity_id.  Must be mp4.
      example: '/tmp/snapshot_{{ entity_id }}.mp4'
    duration:
      description: (Optional) Target recording length (in seconds).
      default: 30
      example: 30
    lookback:
      description: (Optional) Target lookback period (in seconds) to include in addition to duration.  Only available if there is currently an active HLS stream.
      example: 4

onvif_ptz:
  description: If your ONVIF camera supports PTZ, you will be able to pan, tilt or zoom your camera.
  fields:
    entity_id:
      description: "String or list of strings that point at entity_ids of cameras. Else targets all."
      example: "camera.living_room_camera"
    tilt:
      description: "Tilt direction. Allowed values: UP, DOWN, NONE"
      example: "UP"
    pan:
      description: "Pan direction. Allowed values: RIGHT, LEFT, NONE"
      example: "RIGHT"
    zoom:
      description: "Zoom. Allowed values: ZOOM_IN, ZOOM_OUT, NONE"
      example: "NONE"
    distance:
      description: "Distance coefficient. Sets how much PTZ should be executed in one request. Allowed values: floating point numbers, 0 to 1"
      default: 0.1
      example: 0.1
    speed:
      description: "Speed coefficient. Sets how fast PTZ will be executed. Allowed values: floating point numbers, 0 to 1"
      default: 0.5
      example: 0.5
    move_mode:
      description: "PTZ moving mode. ContinuousMode is mandatory if PTZ is supported, RelativeMode and AbsoluteMode are optionals implementations so depending of manufactors willing"
      default: "RelativeMode"
      example: "ContinuousMode"
