start_for:
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "lawn_mower"
  fields:
    duration:
      required: true
      example: 60
      default: 100
      selector:
        number:
          min: 1
          max: 60480
          unit_of_measurement: "min"

park_for:
  target:
    entity:
      integration: "husqvarna_automower"
      domain: "lawn_mower"
  fields:
    duration:
      required: true
      example: 60
      default: 100
      selector:
        number:
          min: 1
          max: 60480
          unit_of_measurement: "min"
