# ScreenLogic Services
set_color_mode:
  name: Set Color Mode
  description: Sets the color mode for all color-capable lights attached to this ScreenLogic gateway.
  target:
    device:
      integration: screenlogic
  fields:
    color_mode:
      name: Color Mode
      description: The ScreenLogic color mode to set
      required: true
      selector:
        select:
          options:
            - all_off
            - all_on
            - american
            - blue
            - caribbean
            - color_set
            - color_swim
            - color_sync
            - green
            - hold
            - magenta
            - next_mode
            - party
            - recall
            - red
            - reset
            - romance
            - royal
            - save
            - sunset
            - thumper
            - white
set_scg:
  name: Set Salt Chlorine Generator
  description: Sets salt chlorine generator runtime percentages for both pool and spa.
  target:
    device:
      integration: screenlogic
  fields:
    pool_percent:
      name: Pool Percentage
      description: The runtime percentage for the salt chlorine generator when in pool mode
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
      default: 50
      example: 100
    spa_percent:
      name: Spa Percentage
      description: The runtime percentage for the salt chlorine generator when in spa mode. Value is treated as a percentage of the pool runtime.
      selector:
        number:
          min: 0
          max: 20
          unit_of_measurement: "%"
      default: 0
      example: 20
