ptz:
  description: Pan/Tilt service for Foscam camera.
  fields:
    entity_id:
      description: Name(s) of entities to move.
      example: 'camera.living_room_camera'
    movement:
      description: "Direction of the movement. Allowed values: UP, DOWN, LEFT, RIGHT, TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT."
      example: 'UP'
    travel_time:
      description: "(Optional) Travel time in seconds. Allowed values: float from 0 to 1. Default: 0.125"
      example: 0.125
