set_time_to:
  description: Control timers to turn the system on or off after a set number of minutes
  fields:
    entity_id:
      description: Time To sensor entity
      example: "sensor.ac_time_to_on"
    minutes:
      description: Minutes until action
      example: "60"
set_myzone:
  description: Change which zone is set as the reference for temperature control
  fields:
    entity_id:
      description: Climate entity
      example: "climate.living_room"
