clean_room:
  target:
    entity:
      integration: "sharkiq"
      domain: "vacuum"

  fields:
    rooms:
      required: true
      advanced: true
      example: "Kitchen"
      default: ""
      selector:
        area:
          multiple: true
