# Describes the format for available timer services

start:
  name: Start
  description: Start a timer
  target:
    entity:
      domain: timer
  fields:
    duration:
      description: Duration the timer requires to finish. [optional]
      default: 0
      example: "00:01:00 or 60"
      selector:
        text:

pause:
  name: Pause
  description: Pause a timer.
  target:
    entity:
      domain: timer

cancel:
  name: Cancel
  description: Cancel a timer.
  target:
    entity:
      domain: timer

finish:
  name: Finish
  description: Finish a timer.
  target:
    entity:
      domain: timer

modify:
  name: Modify
  description: Add / Subtract time from a timer.
  fields:
    duration:
      name: Duration
      description: Duration to add / subtract from the timer. To subtract time, use a negative value.
      example: "00:01:00"
      required: true
      default: 00:01:00
      selector:
        text:

  target:
    entity:
      domain: timer
