set_datetime:
  name: Set Date/Time
  description: Set the date/time for a datetime entity.
  target:
    entity:
      domain: datetime
  fields:
    datetime:
      name: Date & Time
      description: The date/time to set.
      required: true
      example: "2022/11/01 22:15"
      selector:
        datetime:
