# Describes the format for available services for bmw_connected_drive

light_flash:
  description: >
    Flash the lights of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

door_lock:
  description: >
    Lock the doors of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

door_unlock:
  description: >
    Unlock the doors of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

sound_horn:
  description: >
    Sound the horn of the vehicle. The vehicle is identified via the vin
    (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567

activate_air_conditioning:
  description: >
    Start the air conditioning of the vehicle. What exactly is started here
    depends on the type of vehicle. It might range from just ventilation over
    auxilary heating to real air conditioning. The vehicle is identified via
    the vin (see below).
  fields:
    vin:
      description: >
        The vehicle identification number (VIN) of the vehicle, 17 characters
      example: WBANXXXXXX1234567
