# Describes the format for available switch services

turn_on:
  description: Turn a switch on.
  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'switch.living_room'

turn_off:
  description: Turn a switch off.
  fields:
    entity_id:
      description: Name(s) of entities to turn off.
      example: 'switch.living_room'

toggle:
  description: Toggles a switch state.
  fields:
    entity_id:
      description: Name(s) of entities to toggle.
      example: 'switch.living_room'

mysensors_send_ir_code:
  description: Set an IR code as a state attribute for a MySensors IR device switch and turn the switch on.
  fields:
    entity_id:
      description: Name(s) of entities that should have the IR code set and be turned on. Platform dependent.
      example: 'switch.living_room_1_1'
    V_IR_SEND:
      description: IR code to send.
      example: '0xC284'

xiaomi_miio_learn_command:
  description: 'Learn an IR command, press "Call Service", point the remote at the IR device, and the learned command will be shown as a notification in Overview.'
  fields:
      slot:
        description: 'Define the slot used to save the IR command (Value from 1 to 1000000) (Default: 1)'
        example: '"slot": 1'
      timeout:
        description: 'Define the timeout in seconds, before which the command must be learned. (Default: 10)'
        example: '"timeout": 30'

xiaomi_miio_send_command:
  description: 'Send one or more IR commands'
  fields:
    command:
      description: 'Takes a list of base64 encoded commands to send.'
      example: "[ base64 encoded command, base64 encoded command ]"