# Describes the format for available switch services

turn_on:
  description: Turn a switch on

  fields:
    entity_id:
      description: Name(s) of entities to turn on
      example: 'switch.living_room'

turn_off:
  description: Turn a switch off

  fields:
    entity_id:
      description: Name(s) of entities to turn off
      example: 'switch.living_room'

toggle:
  description: Toggles a switch state

  fields:
    entity_id:
      description: Name(s) of entities to toggle
      example: 'switch.living_room'

mysensors_send_ir_code:
  description: Set an IR code as a state attribute for a MySensors IR device switch and turn the switch on.

  fields:
    entity_id:
      description: Name(s) of entites that should have the IR code set and be turned on. Platform dependent.
      example: 'switch.living_room_1_1'

    V_IR_SEND:
      description: IR code to send
      example: '0xC284'

xiaomi_vacuum_command:
  description: Send command to the vacuum.
  fields:
    command:
      description: Command to execute
      example: 'set_dnd_timer'
    params:
      description: Parameters for the command
      example: '[22,0,6,0]'

xiaomi_vacuum_set_fanspeed:
  description: Set the fanspeed.
  fields:
    fanspeed:
      description: Fanspeed, between 0 and 100
      example: '60'

xiaomi_vacuum_remote_control_start:
  description: Start remote control of the vacuum. You can then move it with xiaomi_vacuum_remote_control_move, when done call xiaomi_vacuum_remote_control_stop.

xiaomi_vacuum_remote_control_stop:
  description: Stop remote control mode of the vacuum.

xiaomi_vacuum_remote_control_move:
  description: Remote control the vacuum, make sure you first set it in remote control mode. With xiaomi_vacuum_remote_control_start.
  fields:
    velocity:
      description: Speed, between -0.3 - 0.3
      example: '0.2'
    rotation:
      description: Rotation, between -180 degrees and 180 degrees
      example: '90'
    duration:
      description: Duration of the movement?
      example: '1500'

xiaomi_vacuum_remote_control:
  description: Remote control the vacuum, only makes one move and then stops.
  fields:
    velocity:
      description: Speed, between -0.3 - 0.3
      example: '0.2'
    rotation:
      description: Rotation, between -180 degrees and 180 degrees
      example: '90'
    duration:
      description: Duration of the movement?
      example: '1500'