# Describes the format for available switch services

xiaomi_vacuum_command:
  description: Send command to the vacuum.

  fields:
    entity_id:
      description: Name(s) of entites that should be send a command.
      example: 'switch.mirobo'

    command:
      description: Command to execute
      example: 'set_dnd_timer'

    params:
      description: Parameters for the command
      example: '[22,0,6,0]'

xiaomi_vacuum_set_fanspeed:
  description: Set the fanspeed.

  fields:
    entity_id:
      description: Name(s) of entites that should change fanspeed.
      example: 'switch.mirobo'

    fanspeed:
      description: Fanspeed, 38, 60, 77 or 90
      example: '60'

xiaomi_vacuum_remote_control:
  description: Remote control the vacuum.

  fields:
    entity_id:
      description: Name(s) of entites that should be remote controlled.
      example: 'switch.mirobo'

    velocity:
      description: Speed, between -0.3 - 0.3
      example: '0.2'
    rotation:
      description: Rotation, between -180 degrees and 180 degrees
      example: '90'
    duration:
      description: Duration of the movement?
      example: '1500'