# Describes the format for available services

set_system_mode:
  description: >-
      Set the system mode, either indefinitely, or for a set period, after which it will
      revert to Auto.
  fields:
    mode:
      description: 'One of: Auto, AutoWithEco, Away, DayOff, HeatingOff, or Custom.'
      example: Away
    days:
      description: >-
          The duration in days; used with Away, DayOff, or Custom. The system will
          revert to Auto at midnight (today is day 1).
      example: 2
    hours:
      description: The duration in hours; used only with AutoWithEco.
      example:

reset_system:
  description: >-
      Set the system to Auto mode and reset all the zones to follow their schedules
      (i.e. AutoWithReset mode).

set_zone_override:
  description: >-
      Override a zone's setpoint, either indefinitely, or for a set period, after which
      it will revert to following its schedule.
  fields:
    entity_id:
      description: The entity_id of the evohome zone.
      example: climate.bathroom
    setpoint:
      description: The temperature to be used instead of the scheduled setpoint.
      example: 5.0
    duration:
      description: >-
          The zone will revert to its schedule after this many minutes. If 0 the change
          is until the next scheduled setpoint.
      example: 60
    until:
      description: >-
          Used as an alternative to duration; the zone will revert after this time
          (HH:MM).
      example:

clear_zone_override:
  description: Set a zone to follow its schedule.
  fields:
    entity_id:
      description: The entity_id of the zone.
      example: climate.bathroom

