search:
  description: Emulates opening search screen and entering search keyword.
  fields:
    entity_id:
      description: Name(s) of the entities to search on
      example: "remote.living_room"
    keyword:
      description: Search keyword
      example: "Space Jam"
