# Describes the format for available TVOverlay Notify services

notify:
  fields:
    message:
      required: true
      example: Motion detected at Front door!
      selector:
        text:
    title:
      example: "Motion Alert"
      selector:
        text:
    data:
      required: false
      example: TVOVerlay specific attributes
      selector:
        object:
