# synology-dsm service entries description.

reboot:
  description: Reboots the NAS.
  fields:
    serial:
      description: serial of NAS to reboot; optional when only one is configured.
      example: 1NDVC86409

shutdown:
  description: Shutdown the NAS.
  fields:
    serial:
      description: serial of NAS to shutdown; optional when only one is configured.
      example: 1NDVC86409
