# synology-dsm service entries description.

reboot:
  name: Reboot
  description: Reboot the NAS.
  fields:
    device_id:
      name: Synology DSM
      description: Select the Synology DSM to reboot
      required: true
      selector:
        device:
          integration: synology_dsm

shutdown:
  name: Shutdown
  description: Shutdown the NAS.
  fields:
    device_id:
      name: Synology DSM
      description: Select the Synology DSM to shutdown
      required: true
      selector:
        device:
          integration: synology_dsm

poweron:
  name: Power on
  description: Power on the NAS by WoL.
  fields:
    device_id:
      name: Synology DSM
      description: Select the Synology DSM to poweron
      required: true
      selector:
        device:
          integration: synology_dsm
