# synology-dsm service entries description.

reboot:
  name: Reboot
  description: Reboot the NAS.
  target:
    device:
      integration: synology_dsm
      manufacturer: Synology
    entity:
      integration: none

shutdown:
  name: Shutdown
  description: Shutdown the NAS.
  target:
    device:
      integration: synology_dsm
      manufacturer: Synology
    entity:
      integration: none

poweron:
  name: Power on
  description: Power on the NAS by WoL.
  target:
    device:
      integration: synology_dsm
      manufacturer: Synology
    entity:
      integration: none
