set_zone_moisture_percent:
  name: Set zone moisture percent
  description: Set the moisture percentage of a zone or group of zones.
  target:
    entity:
      integration: rachio
      domain: switch
  fields:
    percent:
      name: Percent
      description: Set the desired zone moisture percentage.
      required: true
      example: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: '%'
start_multiple_zone_schedule:
  name: Start multiple zone schedule
  description: Create a custom schedule of zones and runtimes.
  fields:
    entity_id:
      name: Entity
      description: Name of the zone or zones to run. Zones should all be on the same controller, attempting to start zones on multiple controllers may have undesired results.
      required: true
      example: "switch.front_yard, switch.side_yard"
      selector:
        text:
    duration:
      name: Duration
      description: Number of minutes to run the zone(s). If only 1 duration is given, that time will be used for all zones. If given a list of durations, the durations will apply to the respective zone listed above.
      required: true
      example: 15, 20
      selector:
        object:
pause_watering:
  name: Pause watering
  description: Pause any currently running zones or schedules.
  fields:
    devices:
      name: Devices
      description: Name of controllers to pause. Defaults to all controllers on the account if not provided.
      example: Main House
      selector:
        text:
    duration:
      name: Duration
      description: The time to pause running schedules.
      example: 30
      default: 60
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes
resume_watering:
  name: Resume watering
  description: Resume any paused zone runs or schedules.
  fields:
    devices:
      name: Devices
      description: Name of controllers to resume. Defaults to all controllers on the account if not provided.
      example: Main House
      selector:
        text:
