send_command:
  description: Emulate button press for PlayStation 4.
  fields:
    entity_id:
      description: Name(s) of entities to send command.
      example: 'media_player.playstation_4'
    command:
      description: Button to press.
      example: 'ps'

edit_title_data:
  description: Edit/correct title data and prevent automatic changes to title data.
  fields:
    locked:
      description: Set to 'True' to lock title data / prevent title data from automatically updating. Set to 'False' to have Home Assistant automatically get the current data from the PlayStation Store. Defaults to 'True'.
      example: 'False'
    entity_id: 
      description: Entity ID to get current title attributes from. To only lock the current title data, you may also just specify the entity.
    media_content_id:
      description: The ID or the PlayStation Store SKU ID of the title. Defaults to the ID of the currently playing title if 'entity_id' is specified.
      example: 'CUSA00123'
    media_content_title:
      description: The name for the title. Defaults to the current title. The 'locked' field must be set to 'True' if specified.
      example: 'A Title'
    media_image_url:
      description: A URL directing to an image that will be displayed. You may use images in the local (/config/www/) folder. Defaults to the current url if any. The 'locked' field must be set to 'True' if specified.
      example: 'http://localhost:8123/local/image.jpg'
    media_content_type:
      description: The type of a title. Must be 'game' or 'app'. Defaults to 'game'. The 'locked' field must be set to 'True' if specified.
      example: 'game'
