download_file:
  fields:
    url:
      required: true
      example: "http://example.org/myfile"
      selector:
        text:
    subdir:
      example: "download_dir"
      selector:
        text:
    filename:
      example: "my_file_name"
      selector:
        text:
    overwrite:
      default: false
      selector:
        boolean:
    async:
      default: true
      selector:
        boolean:
    auth_type:
      selector:
        select:
          options:
            - none
            - basic
            - digest
    username:
      example: "my_username"
      selector:
        text:
    password:
      example: "MyPa$$w0rd"
      selector:
        text:
