# Describes the format for available TTS services

say:
  description: Say some things on a media player.
  fields:
    entity_id:
      description: Name(s) of media player entities.
      example: "media_player.floor"
    message:
      description: Text to speak on devices.
      example: "My name is hanna"
    cache:
      description: Control file cache of this message.
      example: "true"
    language:
      description: Language to use for speech generation.
      example: "ru"
    options:
      description: A dictionary containing platform-specific options. Optional depending on the platform.
      example: platform specific
    enqueue:
      description: Add the content to play at the end of the playlist/queue of the device. True/false
      exemple: true

clear_cache:
  description: Remove cache files and RAM cache.
