# Describes the format for available Android TV services

adb_command:
  description: Send an ADB command to an Android TV device.
  fields:
    entity_id:
      description: Name(s) of Android TV entities.
      example: 'media_player.android_tv_living_room'
    command:
      description: Either an action or an ADB shell command.
      example: 'HOME'
