sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: template
    sensors:
      daytodisplay:
        entity_id: sensor.date
        friendly_name: 'Data'
        value_template: '{{ as_timestamp(now()) | timestamp_custom("%d/%m", True) }}'
  - platform: template
    sensors:
       dayofyear:
         entity_id: sensor.date
         friendly_name: 'Numer dnia w roku'
         value_template: "{{ now().strftime('%j') }}"
  - platform: template
    sensors:
       weekofyear:
         entity_id: sensor.date
         friendly_name: 'Numer tygodnia w roku'
         value_template: "{{ now().isocalendar()[1] }}"
binary_sensor:
  - platform: workday
    name: "Dzień pracujący"
    country: PL
