reload:
  name: Reload
  description: Reload all statistics entities.

reset_buffer:
  name: Reset buffer
  description: >-
    Remove stored state values from a statistics sensor.
    A number of most recent state values can be kept in memory.
    By default, all values will be forgotten, which leads to a temporarily unknown state for most statistical characteristics.
    In case both "keep count" and "keep age" are provided, values which meet one of the two conditions are kept.
  target:
    entity:
      # integration: statistics
      domain: sensor
  fields:
    keep_count:
      name: Keep count
      description: Number of most recent state values to be kept in memory.
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 9999
          mode: box
    keep_age:
      name: Keep age
      description: >-
        Maximum age of most recent state values to be kept in memory.
        Set to a number of seconds in UI mode or define as a time period in YAML mode (e.g. 'minutes: 5').
      required: false
      default: 0
      selector:
        number:
          min: 0
          max: 86400
          mode: box
          unit_of_measurement: "s"
