# Describes the format for available siren services

set_volume_level:
  description: Set volume level for siren device.
  target:
    entity:
      domain: siren
  fields:
    volume_level:
      description: New volume level for siren device.
      example: 0.5

set_active_tone:
  description: Set active tone for siren device.
  target:
    entity:
      domain: siren
  fields:
    tone:
      description: New active tone for siren device.
      example: fire

turn_on:
  description: Turn siren device on.
  target:
    entity:
      domain: siren

turn_off:
  description: Turn siren device off.
  target:
    entity:
      domain: siren

toggle:
  description: Toggles a siren device.
  target:
    entity:
      domain: siren
