# Describes the format for available zha services

permit:
  description: Allow nodes to join the ZigBee network.
  fields:
    duration:
      description: Time to permit joins, in seconds
      example: 60

remove:
  description: Remove a node from the ZigBee network.
  fields:
    ieee_address:
      description: IEEE address of the node to remove
      example: "00:0d:6f:00:05:7d:2d:34"

issue_direct_zigbee_bind:
  description: >- 
    Directly bind 2 zigbee devices. This is useful when you want to bind
    a remote like device directly to a light.  
  fields:
    source_entity_id:
      description: Entity id
      example: "binary_sensor.centralite_3130_00e8fb4e_1"
    target_entity_id:
      description: Entity id
      example: "light.sengled_z01a19nae26_03011d28_1"

issue_direct_zigbee_unbind:
  description: >- 
    Remove a direct binding between to zigbee devices.  
  fields:
    source_entity_id:
      description: Entity id
      example: "binary_sensor.centralite_3130_00e8fb4e_1"
    target_entity_id:
      description: Entity id
      example: "light.sengled_z01a19nae26_03011d28_1"

set_zigbee_cluster_attribute:
  description: >- 
    Set attribute value for the specified cluster on the specified entity. 
  fields:
    entity_id:
      description: Entity id
      example: "binary_sensor.centralite_3130_00e8fb4e_1"
    cluster_id:
      description: ZCL cluster to retrieve attributes for
      example: 6
    cluster_type:
      description: type of the cluster (in or out)
      example: "out"
    attribute:
      description: id of the attribute to set
      example: 0
    value:
      description: value to write to the attribute
      example: 0x0001
    manufacturer:
      description: manufacturer code
      example: 0x00FC

issue_zigbee_cluster_command:
  description: >- 
    Issue command on the specified cluster on the specified entity. 
  fields:
    entity_id:
      description: Entity id
      example: "binary_sensor.centralite_3130_00e8fb4e_1"
    cluster_id:
      description: ZCL cluster to retrieve attributes for
      example: 6
    cluster_type:
      description: type of the cluster (in or out)
      example: "out"
    command:
      description: id of the command to execute
      example: 0
    command_type:
      description: type of the command to execute (client or server)
      example: "server"
    args:
      description: args to pass to the command
      example: {}
    manufacturer:
      description: manufacturer code
      example: 0x00FC
