arm_away_instant:
  name: Arm Away Instant
  description: Arm Away with zero entry delay.
  target:
    entity:
      integration: totalconnect
      domain: alarm_control_panel

arm_home_instant:
  name: Arm Home Instant
  description: Arm Home with zero entry delay.
  target:
    entity:
      integration: totalconnect
      domain: alarm_control_panel

bypass_zone:
  name: Bypass Zone
  description: Bypass a TotalConnect zone.
  target:
    entity:
      integration: totalconnect
      domain: alarm_control_panel
  fields:
    zone_id:
      name: Zone ID
      description: The zone number you want to bypass.
      required: true
      example: "12"
