# Describes the format for available switch services

utility_meter_reset:
  description: Resets the counter of an utility meter.
  fields:
    entity_id:
      description: Name(s) of entities to reset 
      example: 'sensor.peak_meter'

utility_meter_start_pause:
  description: Starts or Pauses the counter of an utility meter.
  fields:
    entity_id:
      description: Name(s) of entities to reset 
      example: 'sensor.peak_meter'
