# Describes the format for available webostv services

button:
  name: Button
  description: "Send a button press command."
  fields:
    entity_id:
      name: Entity
      description: Name(s) of the webostv entities where to run the API method.
      required: true
      example: "media_player.living_room_tv"
      selector:
        entity:
          integration: webostv
          domain: media_player
    button:
      name: Button
      description: >-
        Name of the button to press.
      required: true
      example: "LEFT"
      selector:
        select:
          options:
            - "LEFT"
            - "RIGHT"
            - "DOWN"
            - "UP"
            - "HOME"
            - "MENU"
            - "BACK"
            - "ENTER"
            - "DASH"
            - "INFO"
            - "ASTERISK"
            - "CC"
            - "EXIT"
            - "MUTE"
            - "RED"
            - "GREEN"
            - "BLUE"
            - "VOLUMEUP"
            - "VOLUMEDOWN"
            - "CHANNELUP"
            - "CHANNELDOWN"

command:
  name: Command
  description: "Send a command."
  fields:
    entity_id:
      name: Entity
      description: Name(s) of the webostv entities where to run the API method.
      required: true
      example: "media_player.living_room_tv"
      selector:
        entity:
          integration: webostv
          domain: media_player
    command:
      name: Command
      description: >-
        Endpoint of the command.
      required: true
      example: "system.launcher/open"
      selector:
        select:
          options:
            - "api/getServiceList"
            - "audio/setMute"
            - "audio/getStatus"
            - "audio/getVolume"
            - "audio/setVolume"
            - "audio/volumeUp"
            - "audio/volumeDown"
            - "com.webos.applicationManager/getForegroundAppInfo"
            - "com.webos.applicationManager/launch"
            - "com.webos.applicationManager/listLaunchPoints"
            - "com.webos.service.appstatus/getAppStatus"
            - "com.webos.service.ime/sendEnterKey"
            - "com.webos.service.ime/deleteCharacters"
            - "com.webos.service.ime/insertText"
            - "com.webos.service.tv.display/set3DOn"
            - "com.webos.service.tv.display/set3DOff"
            - "com.webos.service.update/getCurrentSWInformation"
            - "media.controls/play"
            - "media.controls/stop"
            - "media.controls/pause"
            - "media.controls/rewind"
            - "media.controls/fastForward"
            - "media.viewer/close"
            - "system/turnOff"
            - "system/turnOn"
            - "system.notifications/createToast"
            - "system.launcher/close"
            - "system.launcher/getAppState"
            - "system/getSystemInfo"
            - "system.launcher/launch"
            - "system.launcher/open"
            - "settings/getSystemSettings"
            - "tv/channelDown"
            - "tv/channelUp"
            - "tv/getChannelList"
            - "tv/getChannelProgramInfo"
            - "tv/getCurrentChannel"
            - "tv/getExternalInputList"
            - "tv/openChannel"
            - "tv/switchInput"
            - "webapp/closeWebApp"
            - "com.webos.service.networkinput/getPointerInputSocket"
            - "externalpq/setExternalPqData"
            - "com.webos.service.apiadapter/audio/getSoundOutput"
            - "com.webos.service.apiadapter/audio/changeSoundOutput"
            - "com.webos.service.tvpower/power/getPowerState"
            - "com.webos.service.tvpower/power/turnOffScreen"
            - "com.webos.service.tvpower/power/turnOnScreen"
    payload:
      name: Payload
      description: >-
        An optional payload to provide to the endpoint in the format of key value pair(s).
      example: >-
        target: https://www.google.com
      advanced: true
      selector:
        object:

select_sound_output:
  name: Select Sound Output
  description: "Send the TV the command to change sound output."
  fields:
    entity_id:
      name: Entity
      description: Name(s) of the webostv entities to change sound output on.
      required: true
      example: "media_player.living_room_tv"
      selector:
        entity:
          integration: webostv
          domain: media_player
    sound_output:
      name: Sound Output
      description: Name of the sound output to switch to.
      required: true
      example: "external_speaker"
      selector:
        text:
