select_option:
  name: Select
  description: Select an option of an select entity.
  target:
    entity:
      domain: select
  fields:
    option:
      name: Option
      description: Option to be selected.
      required: true
      example: '"Item A"'
      selector:
        text:

select_next:
  name: Next
  description: Select next option of an select entity.
  target:
    entity:
      domain: select
  fields:
    cycle:
      name: Cycle
      description: Loop to the first option if the last is currently selected.
      required: false
      default: true
      example: true
      selector:
        boolean:

select_previous:
  name: Previous
  description: Select previous option of an select entity.
  target:
    entity:
      domain: select
  fields:
    cycle:
      name: Cycle
      description: Loop to the last option if the first is currently selected.
      required: false
      default: true
      example: true
      selector:
        boolean:
