# Describes the format for available switch services

reset:
  name: Reset
  description: Resets the counter of an utility meter.
  fields:
    entity_id:
      name: Utility Meter
      description: Name(s) of the utility meter to reset
      example: "utility_meter.energy"
      required: true
      selector:
        entity:
          domain: utility_meter

next_tariff:
  name: Next Tariff
  description: Changes the tariff to the next one.
  fields:
    entity_id:
      description: Name(s) of entities to reset
      example: "utility_meter.energy"
      required: true
      selector:
        entity:
          domain: utility_meter

select_tariff:
  name: Select Tariff
  description: Selects the current tariff of an utility meter.
  fields:
    entity_id:
      name: Entity Id
      description: Name of the entity to set the tariff for
      example: "utility_meter.energy"
      required: true
      selector:
        entity:
          domain: utility_meter
    tariff:
      name: Tariff
      description: Name of the tariff to switch to
      example: "offpeak"
      required: true
      selector:
        text:

calibrate:
  name: Calibrate
  description: Calibrates an utility meter.
  fields:
    entity_id:
      name: Entity Id
      description: Name of the sensor entity belonging to an Utility Meter to calibrate
      example: "sensor.energy_offpeak"
      required: true
      selector:
        entity:
          integration: utility_meter
          domain: sensor

    value:
      name: Value
      description: Value to which set the meter
      example: "100"
      required: true
      selector:
        text:

