get_packages:
  fields:
    package_state:
      selector:
        select:
          multiple: true
          options:
            - "Delivered"
            - "Expired"
            - "In Transit"
            - "Not Found"
            - "Ready to be picked up"
            - "Returned"
            - "Undelivered"
    config_entry_id:
      required: true
      selector:
        config_entry:
          integration: seventeentrack
