image: spencerassistant/{machine}-spencerassistant
shadow_repository: ghcr.io/spencer-assistant
build_from:
  aarch64: "ghcr.io/spencer-assistant/aarch64-spencerassistant:"
  armv7: "ghcr.io/spencer-assistant/armv7-spencerassistant:"
  armhf: "ghcr.io/spencer-assistant/armhf-spencerassistant:"
  amd64: "ghcr.io/spencer-assistant/amd64-spencerassistant:"
  i386: "ghcr.io/spencer-assistant/i386-spencerassistant:"
codenotary:
  signer: notary@spencer-assistant.io
  base_image: notary@spencer-assistant.io
labels:
  io.hass.type: core
  org.opencontainers.image.source: https://github.com/spencer-assistant/core
