# Describes the format for available services for subaru
fetch:
  description: Refreshes data (does not request update from vehicle). The vehicle is identified via the vin (see below).
  target:
  fields:
    vin:
      description: The vehicle identification number (VIN) of the vehicle, 17 characters
      required: true
      example: "JF2ABCDE6L0000001"
      selector:
        text:
