# Describes the format for available Netatmo services
set_light_auto:
  description: Set the camera (Presence only) light in automatic mode.
  fields:
    entity_id:
      description: Entity id.
      example: "light.living_room"

set_schedule:
  description: Set the heating schedule.
  fields:
    schedule_name:
      description: Schedule name.
      example: Standard
    home_name:
      description: Home name.
      example: MyHome