# Describes the format for available Netatmo services
set_camera_light:
  target:
    entity:
      integration: netatmo
      domain: light
  fields:
    camera_light_mode:
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"
            - "auto"

set_schedule:
  target:
    entity:
      integration: netatmo
      domain: climate
  fields:
    schedule_name:
      example: Standard
      required: true
      selector:
        text:

set_preset_mode_with_end_datetime:
  name: Set preset mode with an end datetime
  description: Set preset mode for Netatmo climate device with end datetime.
  target:
    entity:
      integration: netatmo
      domain: climate
  fields:
    preset_mode:
      name: Preset mode
      description: New value of preset mode.
      required: true
      example: "away"
      selector:
        text:
    end_datetime:
      name: End date & time
      description: The end date & time of the preset mode.
      required: true
      example: '"2019-04-20 05:04:20"'
      selector:
        text:

set_persons_home:
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    persons:
      example: "[Alice, Bob]"
      required: true
      selector:
        object:

set_person_away:
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    person:
      example: Bob
      selector:
        text:

register_webhook:
unregister_webhook:
