# Describes the format for available services

set_zone_mode:
  description: >-
      Set the zone to an operating mode.
  fields:
    entity_id:
      description: The zone's entity_id.
      example: climate.bathroom
    mode:
      description: 'The mode, one of: off, override, timer or footprint.'
      example: override
    temperature:
      description: The target temperature. Used only by override mode.
      example: 18.5
    duration:
      description: >-
          The duration of the override. Used only by override mode.  Optional, default 1
          hour, maximum 24 hours.
      example: '{"minutes": 135}'
