lightwave_registration:
  description: Register home assistant with Lightwave WiFi Link hub.
lightwave_deregistration:
  description: De-register all devices from Lightwave WiFi Link hub.


logi_circle_livestream_record:
  description: Take a video recording from the camera's livestream.
  fields:
    entity_id:
      description: Name(s) of entities to create recordings from.
      example: "camera.living_room_camera"
    filename:
      description: Template of a Filename. Variable is entity_id.
      example: "/tmp/snapshot_{{ entity_id }}.mp4"
    duration:
      description: Recording duration in seconds.
      example: 60  