set_auto_on_off_enable:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    day_of_week:
      required: true
      example: mon
      selector:
        select:
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          translation_key: day_of_week
    enable:
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

set_auto_on_off_times:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: lamarzocco
    day_of_week:
      required: true
      example: mon
      selector:
        select:
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          translation_key: day_of_week
    time_on:
      required: true
      example: "05:00:00"
      selector:
        time:
    time_off:
      required: true
      example: "09:00:00"
      selector:
        time:
