set_auto_on_off_enable:
  target:
    entity:
      integration: lamarzocco
      domain: calendar
  fields:
    day_of_week:
      required: true
      example: mon
      selector:
        select:
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          translation_key: day_of_week
    enable:
      required: true
      selector:
        boolean:

set_auto_on_off_times:
  target:
    entity:
      integration: lamarzocco
      domain: calendar
  fields:
    enable:
      required: false
      selector:
        boolean:
    day_of_week:
      required: true
      example: mon
      selector:
        select:
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          translation_key: day_of_week
    time_on:
      required: true
      example: "05:00:00"
      selector:
        time:
    time_off:
      required: true
      example: "09:00:00"
      selector:
        time:
