set_vicare_mode:
  description: Set a ViCare mode.
  fields:
    entity_id:
      description: Name(s) of vicare climate entities.
      example: "climate.vicare_heating"
    command:
      description: ViCare mode. One of "dhw", "dhwAndHeating", "dhwAndHeatingCooling", "forcedReduced", "forcedNormal" or "standby"
      example: "dhw"
