set_timer_level:
  fields:
    timer_level:
      required: true
      default: "level1"
      selector:
        select:
          translation_key: "level_setting"
          options:
            - "level1"
            - "level2"
            - "level3"
            - "level4"
            - "holiday"
            - "breeze"
    time:
      required: true
      default: 0
      selector:
        number:
          min: 0
          max: 1440
          step: 10
          unit_of_measurement: "min"
          mode: slider

set_breeze:
  fields:
    breeze_level:
      required: false
      advanced: false
      default: "level3"
      selector:
        select:
          translation_key: "level_setting"
          options:
            - "level1"
            - "level2"
            - "level3"
            - "level4"
    temperature:
      required: false
      advanced: false
      default: 18
      selector:
        number:
          min: 15
          max: 35
          step: 1
          unit_of_measurement: "°C"
          mode: slider
    activate:
      required: true
      advanced: false
      default: false
      selector:
        boolean:

set_day_night_time:
  fields:
    day:
      required: true
      advanced: false
      default: "7:00:00"
      example: "7:00:00"
      selector:
        time:
    night:
      required: true
      advanced: false
      default: "22:00:00"
      example: "22:00:00"
      selector:
        time:

set_pollution_settings:
  fields:
    day_pollution_level:
      required: false
      advanced: false
      default: "level3"
      selector:
        select:
          translation_key: "level_setting"
          options:
            - "level1"
            - "level2"
            - "level3"
            - "level4"
    night_pollution_level:
      required: false
      advanced: false
      default: "level2"
      selector:
        select:
          translation_key: "level_setting"
          options:
            - "level1"
            - "level2"
            - "level3"
            - "level4"
    humidity_control:
      required: false
      advanced: false
      default: true
      selector:
        boolean:
    airquality_control:
      required: false
      advanced: false
      default: true
      selector:
        boolean:
    co2_control:
      required: false
      advanced: false
      default: true
      selector:
        boolean:
    co2_threshold:
      required: false
      advanced: false
      default: 600
      selector:
        number:
          min: 400
          max: 2000
          step: 50
          unit_of_measurement: "ppm"
          mode: slider
    co2_hysteresis:
      required: false
      advanced: false
      default: 100
      selector:
        number:
          min: 50
          max: 400
          step: 50
          unit_of_measurement: "ppm"
          mode: slider
