set_manual_level:
  fields:
    manual_level:
      required: true
      advanced: false
      default: "Off"
      selector:
        select:
          options:
            - "Off"
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"
            - "Breeze"
            - "Holiday"

set_timer_level:
  fields:
    timer_level:
      required: true
      advanced: false
      default: "Level1"
      selector:
        select:
          options:
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"
            - "Holiday"
            - "Breeze"
    time:
      required: true
      advanced: false
      default: 0
      selector:
        number:
          min: 0
          max: 1440
          step: 10
          unit_of_measurement: "min"
          mode: slider

set_breeze:
  fields:
    breeze_level:
      required: false
      advanced: false
      default: "Level3"
      selector:
        select:
          options:
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"
    temperature:
      required: false
      advanced: false
      default: 18
      selector:
        number:
          min: 15
          max: 35
          step: 1
          unit_of_measurement: "°C"
          mode: slider
    activate:
      required: true
      advanced: false
      default: false
      selector:
        boolean:

set_day_night_time:
  fields:
    day:
      required: true
      advanced: false
      default: false
      selector:
        time:
    night:
      required: true
      advanced: false
      default: false
      selector:
        time:

set_pollution_settings:
  fields:
    day_pollution_level:
      required: false
      advanced: false
      default: "Level3"
      selector:
        select:
          options:
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"
    night_pollution_level:
      required: false
      advanced: false
      default: "Level2"
      selector:
        select:
          options:
            - "Level1"
            - "Level2"
            - "Level3"
            - "Level4"
    humidity_control:
      required: false
      advanced: false
      default: true
      selector:
        boolean:
    airquality_control:
      required: false
      advanced: false
      default: true
      selector:
        boolean:
    co2_control:
      required: false
      advanced: false
      default: true
      selector:
        boolean:
    co2_threshold:
      required: false
      advanced: false
      default: 600
      selector:
        number:
          min: 400
          max: 2000
          step: 50
          unit_of_measurement: "ppm"
          mode: slider
    co2_hysteresis:
      required: false
      advanced: false
      default: 100
      selector:
        number:
          min: 50
          max: 400
          step: 50
          unit_of_measurement: "ppm"
          mode: slider
