set_aircleaner_mode:
  description: "Sets the air cleaner mode. This is a system global mode."
  fields:
    entity_id:
      description: "(Optional) What zone's system to set. Any zone of a particular system will \
      work. Leaving it blank will cause all systems to enter this air cleaner mode."
      example: "climate.master_bed"
    aircleaner_mode:
      description: "The air cleaner mode to set. Options include \"auto\", \"quick\", or \"allergy\"."
      example: "allergy"

set_humidify_setpoint:
  description: "nexia.set_humidify_setpoint will allow you to set the humidification setpoint."
  fields:
    entity_id:
      description: "(Optional) What zone's system to set. Any zone of a particular system will \
      work. Leaving it blank will cause all systems to enter this air cleaner mode."
      example: "climate.master_bed"
    humidity:
      description: "The humidification setpoint as an int, range 35-65."
      example: 45
