# Describes the format for available Flo services

set_sleep_mode:
  description: Set the location into sleep mode.
  fields:
    location_id:
      description: The location id for the Flo device
      example: "123456789"
    sleep_minutes:
      description: The time to sleep in minutes.
      example: 120
    revert_to_mode:
      description: The mode to revert to after sleep_minutes has elapsed.
      example: "home"
set_away_mode:
  description: Set the location into away mode.
  fields:
    location_id:
      description: The location id for the Flo device
      example: "123456789"
set_home_mode:
  description: Set the location into home mode.
  fields:
    location_id:
      description: The location id for the Flo device
      example: "123456789"
run_health_test:
  description: Have the Flo device run a health test.
  fields:
    device_id:
      description: The id for the Flo device to run the test with
      example: "98764321"
