# Describes the format for available Blink services

blink_update:
  description: Force a refresh.

trigger_camera:
  description: Request camera to take new image.
  fields:
    entity_id:
      description: Name(s) of camera entities to take new image.
      example: "camera.living_room_camera"

save_video:
  description: Save last recorded video clip to local file.
  fields:
    name:
      description: Name of camera to grab video from.
      example: "Living Room"
    filename:
      description: Filename to writable path (directory may need to be included in whitelist_dirs in config)
      example: "/tmp/video.mp4"

send_pin:
  description: Send a new pin to blink for 2FA.
  fields:
    pin:
      description: Pin received from blink. Leave empty if you only received a verification email.
      example: "abc123"

bulk_download:
  description: Bulk download videos for one or more cameras.
  fields:
    path:
      description: Filepath to save videos in (directory may need to be included in whitelist_dirs in config)
      example: "/tmp/blink/videos"
    since:
      description: Simple YYYY/MM/DD date format to download all videos from that date to today.
      example: "2020/12/30"
    name:
      description: Optional camera name (as named in your Blink app) or list of camera names. Omitting this results in downloading videos from all cameras.
      example: "[Camera1, Living Room]"
