assume_state:
  name: Assume state
  description: Set Sensibo device to external state.
  target:
    entity:
      integration: sensibo
      domain: climate
  fields:
    state:
      name: State
      description: State to set.
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
enable_timer:
  name: Enable Timer
  description: Enable the timer with custom time.
  target:
    entity:
      integration: sensibo
      domain: climate
  fields:
    minutes:
      name: Minutes
      description: Countdown for timer (for timer state on)
      required: false
      example: 30
      selector:
        number:
          min: 0
          step: 1
          mode: box
enable_pure_boost:
  name: Enable Pure Boost
  description: Enable and configure Pure Boost settings.
  target:
    entity:
      integration: sensibo
      domain: climate
  fields:
    ac_integration:
      name: AC Integration
      description: Integrate with Air Conditioner.
      required: true
      example: true
      selector:
        boolean:
    geo_integration:
      name: Geo Integration
      description: Integrate with Presence.
      required: true
      example: true
      selector:
        boolean:
    indoor_integration:
      name: Indoor Air Quality
      description: Integrate with checking indoor air quality.
      required: true
      example: true
      selector:
        boolean:
    outdoor_integration:
      name: Outdoor Air Quality
      description: Integrate with checking outdoor air quality.
      required: true
      example: true
      selector:
        boolean:
    sensitivity:
      name: Sensitivity
      description: Set the sensitivity for Pure Boost.
      required: true
      example: "Normal"
      selector:
        select:
          options:
            - "Normal"
            - "Sensitive"
full_state:
  name: Set full state
  description: Set full state for Sensibo device
  target:
    entity:
      integration: sensibo
      domain: climate
  fields:
    mode:
      name: HVAC mode
      description: HVAC mode to set
      required: true
      example: "heat"
      selector:
        select:
          options:
            - "cool"
            - "heat"
            - "fan"
            - "auto"
            - "dry"
            - "off"
    target_temperature:
      name: Target Temperature
      description: Optionally set target temperature
      required: false
      example: 23
      selector:
        number:
          min: 0
          step: 1
          mode: box
    fan_mode:
      name: Fan mode
      description: Optionally set fan mode
      required: false
      example: "low"
      selector:
        text:
          type: text
    swing_mode:
      name: swing mode
      description: Optionally set swing mode
      required: false
      example: "fixedBottom"
      selector:
        text:
          type: text
    horizontal_swing_mode:
      name: Horizontal swing mode
      description: Optionally set horizontal swing mode
      required: false
      example: "fixedLeft"
      selector:
        text:
          type: text
    light:
      name: Light
      description: Set light on or off
      required: false
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
