assume_state:
  name: Assume state
  description: Set Sensibo device to external state.
  target:
    entity:
      integration: sensibo
      domain: climate
  fields:
    state:
      name: State
      description: State to set.
      required: true
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
horizontal_swing:
  name: Horizontal swing
  description: Set Sensibo device horizontal swing
  target:
    entity:
      integration: sensibo
      domain: climate
  fields:
    state:
      name: State
      description: State to set.
      required: true
      example: "stopped"
      selector:
        text:
