set_auto_off:
  description: 'Update Switcher device auto off setting.'
  fields:
    auto_off:
      description: 'Time period string containing hours and minutes.'
      example: '"02:30"'

update_device_name:
  description: 'Update Switcher device name setting.'
  fields:
    name:
      description: 'Any string with the minimum length of 2 and the maximum length of 32.'
      example: '"My Switcher Device"'
