set_custom_effect:
  description: Set a custom light effect.
  target:
    entity:
      integration: flux_led
      domain: light
  fields:
    colors:
      description: List of colors for the custom effect (RGB). (Required, Max 16 Colors)
      example: |
        - [255,0,0]
        - [0,255,0]
        - [0,0,255]
    speed_pct:
      description: Effect speed for the custom effect (0-100). (Optional, default 50)
      example: 80
    transition:
      description: Effect transition. (One of gradual, jump, strobe. Default gradual.)
      example: 'jump'
