overlay_audio:
  target:
    entity:
      integration: bang_olufsen
      domain: media_player
    device:
      integration: bang_olufsen
  fields:
    uri:
      required: false
      selector:
        text:
    absolute_volume:
      required: false
      example: 40
      selector:
        number:
          min: 0
          max: 100
    offset_volume:
      required: false
      example: 10
      selector:
        number:
          min: 0
          max: 100
    tts:
      required: false
      example: This is a test
      selector:
        text:
    tts_language:
      required: false
      example: en-us
      selector:
        text:
