found_calendar:
  description: Add calendar if it has not been already discovered.
scan_for_calendars:
  description: Scan for new calendars.
add_event:
  description: Add a new calendar event.
  fields:
    calendar_id:
      description: The id of the calendar you want.
      example: "Your email"
    summary:
      description: Acts as the title of the event.
      example: "Bowling"
    status:
      description: 'Status of the event. Possible values are: "confirmed", "tentative", "cancelled"'
      example: "confirmed"
    send_updates:
      description: 'Acceptable values are: "all": Notifications are sent to all guests. "externalOnly": Notifications are sent to non-Google Calendar guests only. "none": No notifications are sent.'
      example: "all"
    description:
      description: The description of the event. Optional.
      example: "Birthday bowling"
    start_date_time:
      description: The date and time the event should start.
      example: "2019-03-22 20:00:00"
    end_date_time:
      description: The date and time the event should end.
      example: "2019-03-22 22:00:00"
    location:
      description: The location the event will be.
      example: "89 E 42nd St"
    recurrence:
      description: "List of RRULE, EXRULE, RDATE and EXDATE lines for a recurring event, as specified in RFC5545."
      example: "[RRULE:FREQ=DAILY;INTERVAL=1]"
    start_date:
      description: The date the whole day event should start.
      example: "2019-03-10"
    end_date:
      description: The date the whole day event should end.
      example: "2019-03-11"
    in:
      description: Days or weeks that you want to create the event in.
      example: '"days": 2 or "weeks": 2'
    transparency:
      description: 'Whether the event blocks time on the calendar. "opaque": The event does block time on the calendar. "transparent": The event does not block time on the calendar.'
      example: "opaque"
    visibility:
      description: 'Visibility of the event. Possible values are: "default", "public", and "private".'
      example: "default"
