# Describes the format for available Number entity services

set_value:
  description: Set the value of a Number entity.
  fields:
    entity_id:
      description: Entity ID of the Number to set the new value.
      example: number.volume
    value:
      description: The target value the entity should be set to.
      example: 42
decrement:
  description: Decrement the value of a Number entity by its stepping.
  fields:
    entity_id:
      description: Entity id of the Number that should be decremented.
      example: number.volume
increment:
  description: Increment the value of a Number entity by its stepping.
  fields:
    entity_id:
      description: Entity id of the Number that should be incremented.
      example: number.volume
