# Describes the format for available Number entity services

set_value:
  description: Set the value of an Number entity.
  fields:
    entity_id:
      description: Entity id of the Number to set the new value.
      example: number.volume
    value:
      description: The target value the entity should be set to.
      example: 42
